version: '3.4'

services:
  rucio:
    container_name: rucio-dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: debug
    ports:
      - 5678:5678 # ui debug port
      - 5679:5679 # server debug port
      - 5680:5680 # cli debug port
      - 5681:5681 # pytest debug port
      - 5000:5000 # flask ui
      - 443:443 # server port
    volumes:
      - ../tools:/opt/rucio/tools
      - ../bin:/opt/rucio/bin
      - ../lib:/opt/rucio/lib
      - /sys/fs/cgroup:/sys/fs/cgroup
    environment:
      - X509_USER_CERT=/opt/rucio/etc/usercert.pem
      - X509_USER_KEY=/opt/rucio/etc/userkey.pem
      - RDBMS=postgres11
      # - RUCIO_HOST=rucio-devmaany.cern.ch #TODO change
      - RUCIO_HOST=rucio
    privileged: true
  ruciodb:
    image: docker.io/postgres:14
    environment:
      - POSTGRES_USER=rucio
      - POSTGRES_DB=rucio
      - POSTGRES_PASSWORD=secret
    command:
      [
        "-c",
        "fsync=off",
        "-c",
        "synchronous_commit=off",
        "-c",
        "full_page_writes=off"
      ]
  graphite:
    image: docker.io/graphiteapp/graphite-statsd
  fts:
    image: docker.io/rucio/fts
  ftsdb:
    image: docker.io/mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=fts
      - MYSQL_PASSWORD=fts
      - MYSQL_ROOT_PASSWORD=fts
      - MYSQL_DATABASE=fts
  xrd1:
    image: docker.io/rucio/xrootd
    environment:
      - XRDPORT=1094
    volumes:
      - ../etc/certs/hostcert_xrd1.pem:/tmp/xrdcert.pem:Z
      - ../etc/certs/hostcert_xrd1.key.pem:/tmp/xrdkey.pem:Z
  xrd2:
    image: docker.io/rucio/xrootd
    environment:
      - XRDPORT=1095
    volumes:
      - ../etc/certs/hostcert_xrd2.pem:/tmp/xrdcert.pem:Z
      - ../etc/certs/hostcert_xrd2.key.pem:/tmp/xrdkey.pem:Z
  xrd3:
    image: docker.io/rucio/xrootd
    environment:
      - XRDPORT=1096
    volumes:
      - ../etc/certs/hostcert_xrd3.pem:/tmp/xrdcert.pem:Z
      - ../etc/certs/hostcert_xrd3.key.pem:/tmp/xrdkey.pem:Z
  xrd4:
    image: docker.io/rucio/xrootd
    environment:
      - XRDPORT=1097
    volumes:
      - ../etc/certs/hostcert_xrd4.pem:/tmp/xrdcert.pem:Z
      - ../etc/certs/hostcert_xrd4.key.pem:/tmp/xrdkey.pem:Z
  minio:
    image: docker.io/minio/minio
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password
    volumes:
      - ../etc/certs/hostcert_minio.pem:/root/.minio/certs/public.crt:Z
      - ../etc/certs/hostcert_minio.key.pem:/root/.minio/certs/private.key:Z
    command: [ "server", "/data" ]
  activemq:
    image: docker.io/webcenter/activemq:latest
    environment:
      - ACTIVEMQ_CONFIG_NAME=activemq
      - ACTIVEMQ_CONFIG_DEFAULTACCOUNT=false
      - ACTIVEMQ_USERS_fts=supersecret
      - ACTIVEMQ_GROUPS_writes=fts
      - ACTIVEMQ_USERS_receiver=supersecret
      - ACTIVEMQ_GROUPS_reads=receiver
      - ACTIVEMQ_CONFIG_SCHEDULERENABLED=true
  ssh1:
    image: docker.io/rucio/ssh
    network_mode: "service:rucio"
    volumes:
      - ../etc/certs/ssh/ruciouser_sshkey.pub:/tmp/sshkey.pub:Z
