# 1. podman network create rucio
# 2. comment out the extra_hosts and port assignments
services:
  rucio:
    image: docker.io/rucio/rucio-dev
    # container_name: rucio
    network_mode: rucio
    # extra_hosts:
    #   - "ruciodb:127.0.0.1"
    #   - "graphite:127.0.0.1"
    #   - "fts:127.0.0.1"
    #   - "ftsdb:127.0.0.1"
    #   - "xrd1:127.0.0.1"
    #   - "xrd2:127.0.0.1"
    #   - "xrd3:127.0.0.1"
    #   - "xrd4:127.0.0.1"
    #   - "minio:127.0.0.1"
    #   - "activemq:127.0.0.1"
    #   - "ssh1:127.0.0.1"
    # ports:
    #   - "127.0.0.1:8443:443"
    #   - "127.0.0.1:5432:5432"
    #   - "127.0.0.1:8080:80"
    #   - "127.0.0.1:8446:8446"
    #   - "127.0.0.1:8449:8449"
    #   - "127.0.0.1:3306:3306"
    #   - "127.0.0.1:1094:1094"
    #   - "127.0.0.1:1095:1095"
    #   - "127.0.0.1:1096:1096"
    #   - "127.0.0.1:1097:1097"
    #   - "127.0.0.1:9000:9000"
    #   - "127.0.0.1:61613:61613"
    #   - "127.0.0.1:2222:22"
    volumes:
      - ../../../tools:/opt/rucio/tools:Z
      - ../../../bin:/opt/rucio/bin:Z
      - ../../../lib:/opt/rucio/lib:Z
    environment:
      - X509_USER_CERT=/opt/rucio/etc/usercert.pem
      - X509_USER_KEY=/opt/rucio/etc/userkey.pem
      - RDBMS=postgres14
      - USE_PODMAN=1
  ruciodb:
    image: docker.io/postgres:14
    network_mode: rucio
    environment:
      - POSTGRES_USER=rucio
      - POSTGRES_DB=rucio
      - POSTGRES_PASSWORD=secret
      - USE_PODMAN=1
    command: ["-c", "fsync=off","-c", "synchronous_commit=off","-c", "full_page_writes=off"]
  graphite:
    image: docker.io/graphiteapp/graphite-statsd
    network_mode: rucio
    environment:
    - USE_PODMAN=1
  fts:
    image: docker.io/rucio/fts
    network_mode: rucio
  ftsdb:
    image: docker.io/mysql:8
    network_mode: rucio
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=fts
      - MYSQL_PASSWORD=fts
      - MYSQL_ROOT_PASSWORD=fts
      - MYSQL_DATABASE=fts
  xrd1:
    image: docker.io/rucio/xrootd
    container_name: xrd1
    network_mode: rucio
    environment:
      - XRDPORT=1094
    volumes:
      - ../../certs/hostcert_xrd1.pem:/tmp/xrdcert.pem:Z
      - ../../certs/hostcert_xrd1.key.pem:/tmp/xrdkey.pem:Z
  xrd2:
    image: docker.io/rucio/xrootd
    container_name: xrd2
    network_mode: rucio
    environment:
      - XRDPORT=1095
    volumes:
      - ../../certs/hostcert_xrd2.pem:/tmp/xrdcert.pem:Z
      - ../../certs/hostcert_xrd2.key.pem:/tmp/xrdkey.pem:Z
  xrd3:
    image: docker.io/rucio/xrootd
    container_name: xrd3
    network_mode: rucio
    environment:
      - XRDPORT=1096
    volumes:
      - ../../certs/hostcert_xrd3.pem:/tmp/xrdcert.pem:Z
      - ../../certs/hostcert_xrd3.key.pem:/tmp/xrdkey.pem:Z
  xrd4:
    image: docker.io/rucio/xrootd
    container_name: xrd4
    network_mode: rucio
    environment:
      - XRDPORT=1097
    volumes:
      - ../../certs/hostcert_xrd4.pem:/tmp/xrdcert.pem:Z
      - ../../certs/hostcert_xrd4.key.pem:/tmp/xrdkey.pem:Z
  minio:
    image: docker.io/minio/minio
    network_mode: rucio
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password
    volumes:
      - ../../certs/hostcert_minio.pem:/root/.minio/certs/public.crt:Z
      - ../../certs/hostcert_minio.key.pem:/root/.minio/certs/private.key:Z
    command: ["server", "/data"]
  activemq:
    image: docker.io/webcenter/activemq:latest
    network_mode: rucio
    environment:
      - ACTIVEMQ_CONFIG_NAME=activemq
      - ACTIVEMQ_CONFIG_DEFAULTACCOUNT=false
      - ACTIVEMQ_USERS_fts=supersecret
      - ACTIVEMQ_GROUPS_writes=fts
      - ACTIVEMQ_USERS_receiver=supersecret
      - ACTIVEMQ_GROUPS_reads=receiver
      - ACTIVEMQ_CONFIG_SCHEDULERENABLED=true
  ssh1:
    image: docker.io/rucio/ssh
    network_mode: rucio
    volumes:
      - ../../certs/ssh/ruciouser_sshkey.pub:/tmp/sshkey.pub:Z
